### ISSUE TITLE
Dependencies failure to install on arm

### ISSUE THREAD

**Issue by cpstrommen** [LibreCS/vqgarm#4]
On running in an aarm64 docker container, this output:
```bash
Traceback (most recent call last):
  File "generate.py", line 18, in <module>
    from omegaconf import OmegaConf
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/__init__.py", line 1, in <module>
    from .base import Container, DictKeyType, Node, SCMode, UnionNode
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/base.py", line 11, in <module>
    from ._utils import (
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 24, in <module>
    from .grammar_parser import SIMPLE_INTERPOLATION_PATTERN, parse
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/grammar_parser.py", line 12, in <module>
    from .grammar_visitor import (  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/grammar_visitor.py", line 25, in <module>
    from omegaconf.grammar.gen.OmegaConfGrammarLexer import OmegaConfGrammarLexer
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/grammar/gen/OmegaConfGrammarLexer.py", line 257, in <module>
    class OmegaConfGrammarLexer(Lexer):
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/grammar/gen/OmegaConfGrammarLexer.py", line 259, in OmegaConfGrammarLexer
    atn = ATNDeserializer().deserialize(serializedATN())
  File "/usr/local/lib/python3.8/dist-packages/antlr4/atn/ATNDeserializer.py", line 28, in deserialize
    self.checkVersion()
  File "/usr/local/lib/python3.8/dist-packages/antlr4/atn/ATNDeserializer.py", line 50, in checkVersion
    raise Exception("Could not deserialize ATN with version " + str(version) + " (expected " + str(SERIALIZED_VERSION) + ").")
Exception: Could not deserialize ATN with version  (expected 4).
```

On requirements install this output:
```bash
omegaconf 2.2.2 has requirement antlr4-python3-runtime==4.9.*, but you'll have antlr4-python3-runtime 4.10 which is incompatible
tensorboard 2.9.1 has requirement google-auth-oauthlib<0.5,>=0.4.1, but you'll have google-auth-oauthlib 0.5.2 which is incompatible.
tensorboard 2.9.1 has requirement protobuf<3.10,>=3.9.2, but you'll have protobuf 4.21.4 which is incompatible. 
PyTorch-lightning 1.6.5 has requirement protobuf<=3.20.1, but you'll have protobuf 4.21.4 which is incompatible
```
To fix dependencies:

- [x] force antlr4-python-runtime 4.9.*
- [x] force google-auth-oauthlib<0.5,>=0.4.1
- [x] force protobuf<3.10,>=3.9.2
- [x] force protobuf<=3.20.1

**Comment by cpstrommen** [comment]
After appending `requirements.txt` to correct versions:
```bash
ERROR: omegaconf 2.2.2 has requirement antlr4-python3-runtime==4.9.*, but you'll have antlr4-python3-runtime 4.10 which is incompatible.
ERROR: tensorboard 2.9.1 has requirement google-auth-oauthlib<0.5,>=0.4.1, but you'll have google-auth-oauthlib 0.5.2 which is incompatible.
ERROR: tensorboard 2.9.1 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 4.21.4 which is incompatible.
ERROR: pytorch-lightning 1.6.5 has requirement protobuf<=3.20.1, but you'll have protobuf 4.21.4 which is incompatible.
```
Probably a git error, I'll try again

**Comment by cpstrommen** [comment]
Correcting the read errors:
```bash
ERROR: tensorboard 2.9.1 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 3.9.0 which is incompatible.
```
Changed to `protobuf==3.10`, will inform

**Comment by cpstrommen** [comment]
Dependency issue resolved
